name: "install uv"
description: "installs uv using the community action"
runs:
  using: composite
  steps:
    - name: "Install UV"
      shell: bash
      run: |
        curl -LsSf https://astral.sh/uv/install.sh | sh